apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
       - name: vol-1
         mountPath: /mnt
  volumes:
    - name: vol-1
      emptyDir: {}