apiVersion: apps/v1
kind: Deployment
metadata:
  name: taint-deployment
spec:
  replicas: 8
  template:
    metadata:
      name: taint-pods
      labels:
        app: nginx
      selector:
        matchLabels:
          app: nginx

    spec:
       metadata:
          app: nginx
       containers:
       - name: nginx
         image: nginx
         ports:
         - containerPort: 80
